#ifndef PARALLELNEURAL_GLOBAL_H
#define PARALLELNEURAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARALLELNEURAL_LIBRARY)
#  define PARALLELNEURALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PARALLELNEURALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PARALLELNEURAL_GLOBAL_H
